version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - SECRET_KEY=docker-dev-key
      - JWT_SECRET_KEY=docker-jwt-dev-key
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - .:/app