"""add user languages column to psychologists table6

Revision ID: 25ae58e55717
Revises: 651a70429bf4
Create Date: 2025-08-10 16:07:49.668196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ae58e55717'
down_revision = '651a70429bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        #batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        #batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True))
        #batch_op.add_column(sa.Column('remaining_sessions', sa.Integer(), nullable=True))
        #batch_op.add_column(sa.Column('subscription_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('has_used_free_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_used_free_trial')
        batch_op.drop_column('subscription_expiry_date')
        batch_op.drop_column('remaining_sessions')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
