"""Psychologist table add field education

Revision ID: 45a0b701e4ee
Revises: d051306b0d12
Create Date: 2025-08-24 17:56:26.349785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a0b701e4ee'
down_revision = 'd051306b0d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psychologists', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###
